import Head from 'next/head';
import Image from 'next/image';
import { StyledDiv } from './index.styles';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <StyledDiv>
        <h1>Test 1</h1>
        <p>some text</p>
        <button>a button</button>
      </StyledDiv>
    </div>
  );
}
